# File eth_transaction/docker-compose.yml
version: "3.5"

services:
  app:
    image: eth_transaction
    restart: always
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

